### ISSUE TITLE
panic: `Option::unwrap()` on a `None` value at core/src/graph/mod.rs:572:66

### ISSUE THREAD

**Issue by Heliozoa** [getsynth/synth#121]
**Describe the bug**
Panic on calling `synth generate`

**To Reproduce**
1. Schema
users.json
```json
{
    "type": "array",
    "length": {
        "type": "number",
        "subtype": "u64",
        "constant": 1
    },
    "content": {
        "type": "object",
        "id": {
            "type": "number",
            "subtype": "u64",
            "id": {}
        }
    }
}
```
posts.json
```json
{
    "type": "array",
    "length": {
        "type": "number",
        "subtype": "u64",
        "constant": 1
    },
    "content": {
        "type": "object",
        "id": {
            "type": "number",
            "subtype": "u64",
            "id": {}
        },
        "user_id": {
            "type": "same_as",
            "ref": "users.content.id"
        }
    }
}
```
images.json
```json
{
    "type": "array",
    "length": {
        "type": "number",
        "subtype": "u64",
        "constant": 1
    },
    "content": {
        "type": "object",
        "id": {
            "type": "number",
            "subtype": "u64",
            "id": {}
        },
        "post_id": {
            "type": "same_as",
            "ref": "posts.content.id"
        }
    }
}
```
tags.json
```json
{
    "type": "array",
    "length": {
        "type": "number",
        "subtype": "u64",
        "constant": 1
    },
    "content": {
        "type": "object",
        "image": {
            "type": "same_as",
            "ref": "images.content.id"
        }
    }
}
```
2. See error
```console
$ synth generate ns --collection users
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', synth/core/src/graph/mod.rs:572:66
```

**Expected behavior**
Generated data or an error message explaining what's wrong with the schema.

**Environment (please complete the following information):**
 - OS: Ubuntu
 - Version: 21.04

**Additional context**
I was able to reproduce the bug both on the latest release and on master. The schema listed was the most minimal example I was able to find.

**Comment by brokad** [comment]
Thank you @Heliozoa!

There seems to be a class of bugs that worked their way [on top of an old hack](https://github.com/getsynth/synth/blob/d1da60eafea5b7a0cb359d4d95e8f75631f92ccf/core/src/graph/mod.rs#L547).

I will get rid of the hack and this should solve this.
